<?php

function connectDB () :PDO {
    $dbh=new PDO ('mysql:host=db;dbname=Luke-Collection', 'root', 'password');
    return $dbh;
}
/**
 * Function to collect data from the Database and output array.
 *
 * @param $dbh star wars characters data.
 *
 *
 */
function pullSetNames (PDO $dbh) : array {
    $query = $dbh->prepare("SELECT `name`,`alignment`,`forcePower(%)`, `lightsaberPower(%)`,`blasterPower(%)`, `image` FROM `star_wars_characters`");
    $query->setFetchMode(PDO::FETCH_ASSOC);
    $query->execute();
    $result = $query->fetchall();
    $sets = $result;
    return $sets;

}

    /**
     * Function to  output data in different card formats.
     *
     * @param $sets star wars characters data. Data is : Name, alignment, force power, lightsaber power, blaster power
     * and an image.
     *
     */
    function cardContainer(array $sets) : string {
        $result = '';
        foreach ($sets as $set) {
            $result .= '<div class=sets> <div class="text"><h1>' . $set['name'] . '</h1><h2> Alignment: ' . $set['alignment'] . '</h2>
                       <h2>Force Power (%): ' . $set['forcePower(%)'] . ' </h2>
                   <h2>Lightsaber Power (%): ' . $set['lightsaberPower(%)'] . ' </h2>
                   <h2>Blaster Power (%): ' . $set['blasterPower(%)'] . ' </h2></div>
                  <div class="image"> <img src=" ' . $set['image'] . '"/></div></div>';
        }
        return $result;
    }

/**
* Takes the array generated by user on formPage.php and adds to database
*
* @param $values array of the user's input from formPage.php
*
* @param $connection array of current contents of DB we're inserting into.
 *
 * @param connectDb: Connects to data base.
 *
 * @param name : the name the user will input. Varchar type.
 *
 * @param alignment: the faction of the character. Boolean type
 *
 * @param forcePower: The character's force power. Int. Min 1 to max 100 in percentage.
 *
 * @param lighsaberPower: The character's lightsaber power. Int. Min 1 to max 100 in percentage.
 *
 * @param blasterPower: The character's blaster power. Int. Min 1 to max 100 in percentage.
 *
 * @param image: The character's avatar in jpg. Not working the way I want it to yet.
*
* @returns user-generated data to DB
 *
 *
*/
function addDataToDb(PDO $connectDB, $name, $alignment, $forcePower, $lightsaberPower, $blasterPower, $image)
{
    $query = $connectDB->prepare('INSERT INTO `star_wars_characters` (`name`, `alignment`, `forcePower(%)`, `lightsaberPower(%)`, `blasterPower(%)`, `image`)
    VALUES (:name, :alignment, :forcePower, :lightsaberPower, :blasterPower, :image);');

    $query->bindParam(':name', $name, PDO::PARAM_STR, 10);
    $query->bindParam(':alignment', $alignment, PDO::PARAM_STR, 8);
    $query->bindParam(':forcePower', $forcePower, PDO::PARAM_INT, 3);
    $query->bindParam(':lightsaberPower', $lightsaberPower, PDO::PARAM_INT, 3);
    $query->bindParam(':blasterPower', $blasterPower, PDO::PARAM_INT, 3);
    $query->bindParam(':image', $image, PDO::PARAM_STR, 255);
    return $query->execute();
}

